### ISSUE TITLE
Can't list when the upload was done with another tool

### ISSUE THREAD

**Issue by michelpereira** [basak/glacier-cli#12]
I'm opening a new issue related to https://github.com/basak/glacier-cli/issues/10, done more tests and got a conclusion that when you upload with another tool (like FastGlacier) you can't download the file back using glacier-cli.

But everything works OK when you upload and download using glacier-cli, I think the files can't be related to the tool that was used to upload.

Please give more information on how to debug this for you.

Thank you

**Comment by aspiers** [comment]
Is this still an issue?
