### ISSUE TITLE
Installation instructions are out of date

### ISSUE THREAD

**Issue by aspiers** [basak/glacier-cli#49]
"Check out the glacier branch of boto from Github (this branch is not released yet and is still under heavy development)." but this is not true - the branch only has 2 commits which are not in `master`:

https://github.com/boto/boto/compare/glacier

and even those changes (i.e. adding a `description` parameter) seem to be already upstream.

**Comment by basak** [comment]
Yeah it was once true but is no more. Pull requests to fix the documentation welcome.
