### ISSUE TITLE
Current project status?

### ISSUE THREAD

**Issue by aspiers** [basak/glacier-cli#50]
There have been no commits for almost 2 years, and the installation instructions seem out of date, as reported in #49.  This leads me to wonder if the project is still maintained?  It seems that [other forks are more active](https://github.com/basak/glacier-cli/network).  Thanks for any info you can shed.

**Comment by basak** [comment]
As far as I'm concerned it is still maintained, but pretty much feature complete. The only main bug I'm concerned about is #46, and the tough thing to fix there is the migration path for older caches. Packaging and documentation could do with improvement (eg. #47). Apart from that my point of view is that glacier-cli is mainly feature complete, works as intended and so doesn't need to be "active".

**Comment by aspiers** [comment]
OK great, thanks for the info and rapid reply!

**Comment by soxofaan** [comment]
> my point of view is that glacier-cli is mainly feature complete

wouldn't it make sense then to bump the version number to `1.0.0` ? Current version at the moment is `0.1.0` which does not signal "feature complete"

**Comment by basak** [comment]
> wouldn't it make sense then to bump the version number to `1.0.0` ? Current version at the moment is `0.1.0` which does not signal "feature complete" :)

Sure. Maybe we should fully convert to Python 3 (shebangs etc), and also sort out CI in Travis or similar. There are (were?) some tests, but I'm not sure if they've rotted.

**Comment by soxofaan** [comment]
> Maybe we should fully convert to Python 3 (shebangs etc)

changing shebangs is not necessary, if you install glacier-cli with `pip install .` the generated `glacier-cli` script automatically has a shebang with the python version you used to install it.

concerning the tests and travis I created  #79
