### ISSUE TITLE
Any plan to incorporate packaging improvements into the master branch?

### ISSUE THREAD

**Issue by elgow** [basak/glacier-cli#64]
In issue #50 you said "Packaging and documentation could do with improvement". Markus Hubig has added requirements.txt and setup.py in his branch [here](https://github.com/mhubig/glacier-cli@develop). His changes permit installation of glacier-cli with pip, which is always a good thing, using that URL. Will you please consider pulling Markus' changes into the master branch?

**Comment by elgow** [comment]
Thank you for merging the packaging info. pip install git+https://github.com/basak/glacier-cli.git works perfectly.

**Comment by basak** [comment]
On Mon, Feb 15, 2016 at 06:01:46PM -0800, elgow wrote:
> Thank you for merging the packaging info. pip install git+https://github.com/basak/glacier-cli.git works perfectly. 

No problem, and thank you for confirming! If you'd like to modify the
documentation to improve the installation instructions for that use
case, I'd be happy to accept that.

Thanks,

Robie
