### ISSUE TITLE
Error when using ca-central-1 region (stacktrace included in description)

### ISSUE THREAD

**Issue by fizzup** [basak/glacier-cli#69]
Installation is working correctly for us-west-1 (and others), but not for ca-central-1:

```
./glacier.py --region ca-central-1 vault list
Traceback (most recent call last):
  File "./glacier.py", line 736, in <module>
    main()
  File "./glacier.py", line 732, in main
    App().main()
  File "./glacier.py", line 710, in __init__
    cache = Cache(get_connection_account(connection))
  File "./glacier.py", line 330, in get_connection_account
    return connection.layer1.aws_access_key_id
AttributeError: 'NoneType' object has no attribute 'layer1'
```

**Comment by fizzup** [comment]
Ugh. I think this may be a problem with the underlying boto package, which doesn't seem to support ca-central-1. If this is the case, please comment and I will raise an issue for boto.

**Comment by basak** [comment]
That's right. glacier-cli doesn't do anything with the region string apart from to pass it to boto. You need to use a version of boto that supports ca-central-1.
